---
- name: Install OpenSSH server
  hosts: all
  become: true
  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install OpenSSH server
    apt:
      name: openssh-server
      state: present
